apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-crds/base
  - ../../katib-crds/overlays/ihome-application
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-crds
