apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  labels:
    component: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: envoy
  template:
    metadata:
      labels:
        component: envoy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: container
        image: docker.io/chongchuanbing/ml-pipeline.envoy:metadata-grpc:metadata-grpc
        ports:
        - name: md-envoy
          containerPort: 9090
        - name: envoy-admin
          containerPort: 9901
