apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Control pane
  - ../../../admission-webhook/webhook/ihome
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - config/params.env
  name: kubeflow-config
vars:
# We need to define vars at the top level otherwise we will get
# conflicts.
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
