apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mysql
  app.kubernetes.io/component: mysql
  app.kubernetes.io/name: mysql
resources:
- ../../../upstream/env/platform-agnostic/mysql
- ../../overlays/application/application.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.mysql:5.6
  newTag: '5.6'
  newName: docker.io/chongchuanbing/ml-pipeline.mysql:5.6
