apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cache-deployer-role.yaml
- cache-deployer-rolebinding.yaml
- cache-deployer-deployment.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.cache-deployer:1.0.0
  newTag: 1.0.0
