apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Control pane
  - ../../admission-webhook/webhook/ihome
  - ../../common/centraldashboard/overlays/ihome-stacks
  - ../../kubeflow-roles/base
  - ../../jupyter/jupyter-web-app/ihome-base_v3
  - ../../jupyter/notebook-controller/ihome-base_v3
  - ../../profiles/ihome-base_v3
  # Training Operators
  - ../../pytorch-job/pytorch-job-crds/overlays/application
  - ../../pytorch-job/pytorch-operator/overlays/application
  - ../../tf-training/tf-job-crds/overlays/application
  - ../../tf-training/tf-job-operator/overlays/application
  - ../../mxnet-job/mxnet-operator/overlays/application
  - ../../mpi-job/mpi-operator/overlays/application
  - ../../katib/installs/ihome-katib-standalone
  # Pipelines
  - ../../pipeline/minio/installs/ihome
  - ../../pipeline/mysql/installs/ihome
  - ../../pipeline/installs/multi-user
  - ../../argo/ihome-base_v3
  # Serving components
  - ../../seldon/seldon-core-operator/overlays/application
  # Metadata
  - ../../metadata/ihome-v3
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- envs:
  - config/params.env
  name: kubeflow-config
vars:
# We need to define vars at the top level otherwise we will get
# conflicts.
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldpath: metadata.namespace
  name: katib-ui-namespace
  objref:
    kind: Service
    name: katib-ui
    apiVersion: v1
