apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../components/ihome-katib-crds
  - ../../components/ihome-katib-controller
  - ../../components/ihome-katib-db-manager
  - ../../components/ihome-katib-db-mysql
