apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mysql
  app.kubernetes.io/component: mysql
  app.kubernetes.io/name: mysql
resources:
- ../../../upstream/env/platform-agnostic/mysql
- application.yaml
images:
- name: harbor.ihomefnt.com/ai/ml-pipeline.mysql
  newTag: '5.6'
  newName: harbor.ihomefnt.com/ai/ml-pipeline.mysql
