apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-persistenceagent
resources:
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- service-account.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.persistenceagent:0.2.5
  newTag: 0.2.5
  newName: docker.io/chongchuanbing/ml-pipeline.persistenceagent:0.2.5
