apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - katib-configmap.yaml
  - katib-controller-deployment.yaml
  - katib-controller-rbac.yaml
  - katib-controller-secret.yaml
  - katib-controller-service.yaml
  - katib-ui-deployment.yaml
  - katib-ui-rbac.yaml
  - katib-ui-service.yaml
  - trial-template-configmap.yaml
  - trial-template-configmap-labeled.yaml
