apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
- webhook-configuration.yaml
commonLabels:
  kustomize.component: knative
images:
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.activator:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.activator:lastest
  digest: sha256:c51023e62e351d5910f92ee941b4929eb82539e62636dd3ccb4a016d73e86b2e
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.autoscaler-hpa:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.autoscaler-hpa:lastest
  digest: sha256:75da5ff75bc1e71799d039846b1bbd632343894c88feaa59914cfeeb1b213c81
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.autoscaler:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.autoscaler:lastest
  digest: sha256:998a405454832cda18a4bf956d26d610a2df2130a39b834b597a89a3153c8c15
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.networking.istio:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.networking.istio:lastest
  digest: sha256:61461fa789e19895d7d1e5ab96d8bb52a63788e0607e1bd2948b9570efeb6a8f
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.webhook:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.webhook:lastest
  digest: sha256:d07560cd5548640cc79abc819608844527351f10e8b0a847988f9eb602c18972
- name: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.controller:lastest
  newName: docker.io/chongchuanbing/knative-releases.knative.dev.serving.cmd.controller:lastest
  digest: sha256:1e77bdab30c8d0f0df299f5fa93d6f99eb63071b9d3329937dff0c6acb99e059
