apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: notebook-controller
  app.kubernetes.io/component: notebook-controller
  app.kubernetes.io/name: notebook-controller
  kustomize.component: notebook-controller
configMapGenerator:
- literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  name: notebook-controller-config
images:
- name: harbor.ihomefnt.com/ai/kubeflow-images-public.notebook-controller
  newName: harbor.ihomefnt.com/ai/kubeflow-images-public.notebook-controller
  newTag: vmaster-gf39279c0
kind: Kustomization
namePrefix: notebook-controller-
namespace: kubeflow
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- ../overlays/ihome-application
