apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  app: ml-pipeline-scheduledworkflow
resources:
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.scheduledworkflow:0.2.5
  newTag: 0.2.5
  newName: docker.io/chongchuanbing/ml-pipeline.scheduledworkflow:0.2.5
