apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline
resources:
- config-map.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.api-server:0.2.5
  newTag: 0.2.5
  newName: docker.io/chongchuanbing/ml-pipeline.api-server:0.2.5
