apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.yaml
  - config-map.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - secret.yaml
  - statefulset.yaml
  - service.yaml
  - webhook.yaml
