apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: docker.io/chongchuanbing/kubeflow-images-public.pytorch-operator:v0.6.0-18-g5e36a57
  newName: docker.io/chongchuanbing/kubeflow-images-public.pytorch-operator:v0.6.0-18-g5e36a57
  newTag: vmaster-gd596e904
