apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemon-set.yaml
commonLabels:
  kustomize.component: gpu-driver
images:
- name: docker.io/chongchuanbing/google-containers.pause:2.0
  newName: docker.io/chongchuanbing/google-containers.pause:2.0
  newTag: '2.0'
- name: cos-nvidia-installer
  newName: cos-nvidia-installer
  newTag: fixed
