apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cert.yaml
- config-map.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- secret.yaml
- statefulset.yaml
- service.yaml
- webhook.yaml
commonLabels:
  kustomize.component: kfserving
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
- envs:
  - params.env
  name: kfserving-config
vars:
- name: registry
  objref:
    kind: ConfigMap
    name: kfserving-config
    apiVersion: v1
  fieldref:
    fieldpath: data.registry
configurations:
- params.yaml
images:
- name: docker.io/chongchuanbing/kubebuilder.kube-rbac-proxy:v0.4.0
  newName: docker.io/chongchuanbing/kubebuilder.kube-rbac-proxy:v0.4.0
  newTag: v0.4.0
- name: $(registry)/kfserving-controller
  newName: $(registry)/kfserving-controller
  newTag: v0.3.0
