apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-controller/base/katib-configmap.yaml
  - ../../katib-controller/base/katib-controller-deployment.yaml
  - ../../katib-controller/base/katib-controller-rbac.yaml
  - ../../katib-controller/base/katib-controller-secret.yaml
  - ../../katib-controller/base/katib-controller-service.yaml
  - ../../katib-controller/base/katib-ui-deployment.yaml
  - ../../katib-controller/base/katib-ui-rbac.yaml
  - ../../katib-controller/base/katib-ui-service.yaml
  - ../../katib-controller/base/trial-template-configmap.yaml
  - ../../katib-controller/base/trial-template-configmap-labeled.yaml
  - ../../katib-controller/overlays/application/application.yaml
  - ../../katib-controller/overlays/istio/katib-ui-virtual-service.yaml
images:
  - name: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-controller:917164a
    newTag: 917164a
    newName: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-controller:917164a
  - name: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-ui:917164a
    newTag: 917164a
    newName: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-ui:917164a
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
configurations:
  - ../../katib-controller/overlays/istio/params.yaml
