apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-controller/base/katib-db-manager-deployment.yaml
  - ../../katib-controller/base/katib-db-manager-service.yaml
images:
  - name: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-db-manager:917164a
    newTag: 917164a
    newName: docker.io/chongchuanbing/kubeflow-images-public.katib.v1alpha3.katib-db-manager:917164a
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
