apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-controller/base/katib-db-manager-deployment.yaml
  - ../../katib-controller/base/katib-db-manager-service.yaml
images:
  - name: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-db-manager
    newTag: 917164a
    newName: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-db-manager
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
