apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../katib-controller/ihome-katib-controller-base
  - ../../katib-controller/overlays/ihome-application
  - ../../katib-controller/overlays/ihome-istio
images:
  - name: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-controller
    newTag: 917164a
    newName: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-controller
  - name: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-ui
    newTag: 917164a
    newName: harbor.ihomefnt.com/ai/kubeflow-images-public.katib.v1alpha3.katib-ui
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller
configurations:
  - params.yaml
