apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- metadata-writer
resources:
- ml-pipeline-apiserver-deployment.yaml
- ml-pipeline-apiserver-role.yaml
- ml-pipeline-apiserver-rolebinding.yaml
- ml-pipeline-apiserver-sa.yaml
- ml-pipeline-apiserver-service.yaml
- ml-pipeline-persistenceagent-deployment.yaml
- ml-pipeline-persistenceagent-role.yaml
- ml-pipeline-persistenceagent-rolebinding.yaml
- ml-pipeline-persistenceagent-sa.yaml
- ml-pipeline-scheduledworkflow-deployment.yaml
- ml-pipeline-scheduledworkflow-role.yaml
- ml-pipeline-scheduledworkflow-rolebinding.yaml
- ml-pipeline-scheduledworkflow-sa.yaml
- ml-pipeline-ui-deployment.yaml
- ml-pipeline-ui-configmap.yaml
- ml-pipeline-ui-role.yaml
- ml-pipeline-ui-rolebinding.yaml
- ml-pipeline-ui-sa.yaml
- ml-pipeline-ui-service.yaml
- ml-pipeline-viewer-crd-role.yaml
- ml-pipeline-viewer-crd-rolebinding.yaml
- ml-pipeline-viewer-crd-deployment.yaml
- ml-pipeline-viewer-crd-sa.yaml
- ml-pipeline-visualization-deployment.yaml
- ml-pipeline-visualization-sa.yaml
- ml-pipeline-visualization-service.yaml
- pipeline-runner-role.yaml
- pipeline-runner-rolebinding.yaml
- pipeline-runner-sa.yaml
- container-builder-sa.yaml
- viewer-sa.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.api-server:0.2.5
  newTag: 1.0.0
- name: docker.io/chongchuanbing/ml-pipeline.persistenceagent:0.2.5
  newTag: 1.0.0
- name: docker.io/chongchuanbing/ml-pipeline.scheduledworkflow:0.2.5
  newTag: 1.0.0
- name: docker.io/chongchuanbing/ml-pipeline.frontend:0.2.5
  newTag: 1.0.0
- name: docker.io/chongchuanbing/ml-pipeline.viewer-crd-controller:dummy
  newTag: 1.0.0
- name: docker.io/chongchuanbing/ml-pipeline.visualization-server:0.2.5
  newTag: 1.0.0
