apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: docker.io/chongchuanbing/ml-pipeline.inverse-proxy-agent:dummy
  newTag: 1.0.0
resources:
- proxy-configmap.yaml
- proxy-deployment.yaml
- proxy-role.yaml
- proxy-rolebinding.yaml
- proxy-sa.yaml
