apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
- deployment.yaml
- service.yaml
images:
- name: harbor.ihomefnt.com/ai/ml-pipeline.visualization-server
  newTag: 0.2.5
  newName: harbor.ihomefnt.com/ai/ml-pipeline.visualization-server
