apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
- deployment.yaml
- service.yaml
images:
- name: docker.io/chongchuanbing/ml-pipeline.visualization-server:0.2.5
  newTag: 0.2.5
  newName: docker.io/chongchuanbing/ml-pipeline.visualization-server:0.2.5
