apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: service
  selector:
    matchLabels:
      app: application-controller
  template:
    metadata:
      labels:
        app: application-controller
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: manager
        command:
        - /root/manager
        image: docker.io/chongchuanbing/kubeflow-images-public.kubernetes-sigs.application:1.0-beta
        imagePullPolicy: Always
        env:
        # TODO(https://github.com/kubeflow/manifests/issues/1043)
        # Do we really need this?
        - name: project
          value: $(project)
      serviceAccountName: service-account
  volumeClaimTemplates: []
