apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- job.yaml
- certificate.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: harbor.ihomefnt.com/ai/kubeflow-images-public.ingress-setup
  newName: harbor.ihomefnt.com/ai/kubeflow-images-public.ingress-setup
  newTag: latest
