apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: manager
        image: docker.io/chongchuanbing/kubeflow-images-public.notebook-controller:v1.1.0-gd3377cbd:v20190614-v0-160-g386f2749-e3b0c4
        command:
          - /manager
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      serviceAccountName: service-account
